# GitHub Sponsors
github: [CoWork-OS]

# Other funding options (uncomment and add your links if applicable)
# ko_fi: your_username
# patreon: your_username
# open_collective: your_project
# custom: ["https://your-link.com"]
